### ISSUE TITLE
Sphinx Notes/Warnings icon generated as '?'

### ISSUE THREAD

**Issue by Sachin-Suresh** [useblocks/sphinx-simplepdf#13]
Not sure if this is happening only in `sphinx_rtd_theme`.

The generated PDF has Notes/warnings icon displayed as '?'

![image](https://user-images.githubusercontent.com/16320168/189138982-b2e91fdf-687b-406c-8f59-d75616a8b66d.png)

**Comment by danwos** [comment]
Mhh strange, I have different icons in my demo.pdf.
But I also fixed some fonts issues in the last hour, maybe the `?` is an indicator of a not resolvable symbol.

In the DEMO PDF it looks like this:
![image](https://user-images.githubusercontent.com/998700/190346453-8bd3ee19-dcea-4944-91bd-4e05fd45cb59.png)

I close this issue, as I see a high chance that it got fixed. If not, please feel free to reopen.
