### ISSUE TITLE
Title with incorrect whitespaces

### ISSUE THREAD

**Issue by Sachin-Suresh** [useblocks/sphinx-simplepdf#14]
My `conf.py` has:

```
# -- Project information

project = 'Demo Versions'
```

This is the PDF version with the incorrect whitespace.

![image](https://user-images.githubusercontent.com/16320168/189139596-19d5bde5-f3fc-4691-93a2-e615e39effc7.png)

**Comment by danwos** [comment]
It looks good in our Demo PDF, when using the same project name.
So I'm afraid this is font specific and based on the installed fonts.

![image](https://user-images.githubusercontent.com/998700/190336453-3cec7069-0f94-4634-b880-2757d259737a.png)

Currently "Helvetica Neue" is used for the cover, if this is not available, "sans-serif" is set and the browser/os selects the font to go.
I would guess that is the reason.

I'm on it to replace the configured proprietary fonts with some open-source fonts and deliver them with this package.
This is already the case, except for the fonts used on the cover :/

**Comment by danwos** [comment]
See #23, which got already solved.
Sphinx-SimplePDF is now using the "Work Sans" font for the title, which is also included in the package.
So hopefully it looks now the same on all machines.
