### ISSUE TITLE
Add debug option - show used Python interpreter and relevant packages on last PDF page

### ISSUE THREAD

**Issue by 1kastner** [useblocks/sphinx-simplepdf#24]
Just a feature request - I was struggling to create a PDF in https://github.com/useblocks/sphinx-simplepdf/issues/9 and I want to rule out that the issue is related to a poorly configured environment on my side. Therefore, a debug option would be great. My suggestion is that once the debug option is active, the last page(s) of the PDF shows the used Python interpreter and relevant packages. I do not care about styling, it just needs to be functional. Thanks a lot for the project and your effort!

**Comment by danwos** [comment]
Good point, I use similar methods also in other projects.

We could add a page, similar to "cover.html", to the theme.
It gets included only if ``sphinxpdf_debug = True" is set in `conf.py`.
And it gets its data from 1-2 jinja functions, which are able to collect the needed information.

The realization will need some time on my side, too many other projects at the moment :(

**Comment by 1kastner** [comment]
Reminder to myself: The variable is called `simplepdf_debug` and works perfectly!
