### ISSUE TITLE
Missing section number in front of the section names (html and pdf)

### ISSUE THREAD

**Issue by kreuzberger** [useblocks/sphinx-simplepdf#27]
Ok, my index.rst uses toctree :numbered:
The generated html has a numbered toc after the cover page, but the <hx> entries in the html have not. I attached the pdf from the demo as example. The toc is numbered, the sections in the pdf are not.
I am using Sphinx 4.5.0. Maybe this is the issue. 

[Sphinx-SimplePDF-DEMO.pdf](https://github.com/useblocks/sphinx-simplepdf/files/9582823/Sphinx-SimplePDF-DEMO.pdf)

_Originally posted by @kreuzberger in https://github.com/useblocks/sphinx-simplepdf/issues/19#issuecomment-1249155694_

**Comment by kreuzberger** [comment]
I currently have no idea there it comes from. 
* The normal singlehtml build works fine
* commenting out the section in the simplepdf.py builder (`__init__`) shows the "normal" theme without section names too
```
       if self.app.config.html_theme != "simplepdf_theme":
            print("Setting theme to sphinx_simplepdf")
```
* copying the "overwritten" parts in the simplepdf build from Singlehtml build (the ones included by the super()) has also no effects

**Comment by sachin-suresh-rapyuta** [comment]
@kreuzberger - Off topic, I was curious to know your configuration for the "page numbers" for `top-left-content` and "section titles" for `top-right-content`?

**Comment by danwos** [comment]
@sachin-suresh-rapyuta That's the default configuration.

Not used anymore for the DEMO PDF, to test certain things.
But each other PDF should start with this config.

The default config can be found in this file:
https://github.com/useblocks/sphinx-simplepdf/blob/main/sphinx_simplepdf/themes/simplepdf_theme/static/styles/sources/_variables.scss
```scss
$top-left-content: config('top-left-content', 'counter(page)') !default;
$top-center-content: config('top-center-content', '') !default;
$top-right-content: config('top-right-content', 'string(heading)') !default;
```
So its `counter(page)` for `top-left-content` and `string(heading)` for `top-right-content`.

These magic strings are coming from the [weasyprint](https://doc.courtbouillon.org/weasyprint/stable/) library.
Unfortunately I haven't found a nice overview for these magic strings yet.

**Comment by sachin-suresh-rapyuta** [comment]
Oh, that was silly to ask, `'bottom-right-content'` already had this. Thanks, @danwos!

**Comment by kreuzberger** [comment]
Seems the error with the section numbers comes from sphinx, where concrete name checks are used to identfy the build to add section and figure numbers. Refer to the Sphinx issue provided here

**Comment by kreuzberger** [comment]
Due to the answers in https://github.com/sphinx-doc/sphinx/issues/11640 the desired way to be is to have a custom simplepdf writer (could extend Html5Translator) to get the two functions (sectionnumber and fignumber) implemented properly

**Comment by danwos** [comment]
Interesting and thanks for diving deeper into the root cause.
Do you have some time to create such a customized writer?
I'm currently totally overloaded with other projects, but happy to test stuff if needed.
