### ISSUE TITLE
Throws warnings for theme configurations

### ISSUE THREAD

**Issue by twodrops** [useblocks/sphinx-simplepdf#3]
The sphinx-simplepdf builder throws warnings if theme specific configurations are used in `conf.py`.

For example the config needed for RTD theme,

```
html_theme_options = {
    'collapse_navigation': False
}
```

throws

```
WARNING: unsupported theme option 'collapse_navigation' given
```

Perhaps because of the incompatibility with html theme used by sphinx-simplepdf?

**Comment by danwos** [comment]
Added a fix for this on `main` branch.
It simply overwrittes `html_theme_options` if Sphinx-SimplePDF builder is used.
So Sphinx should not claim about unsupported theme options anymore
