### ISSUE TITLE
Blank page with index.rst title appears after ToC

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [useblocks/sphinx-simplepdf#37]
After the ToC, a blank page is displayed with the title being picked from the `index.rst` file. 

Eg: If my index.rst file has

`index.rst`

```
User Doc
=======

Some content here...
```

The PDF has an empty page (after Toc) with "User Doc" displayed.

**Comment by sachin-suresh-rapyuta** [comment]
Can be fixed in custom CSS something like:

```
div.title p.subtitle-cover{
  display: none;
}
```

**Comment by kreuzberger** [comment]
For me the suggested solution removed content form the cover page.
```
div.body h1{
  display: none;
}
```
Seems to remove it
