### ISSUE TITLE
Table width overflow for 3 or more columns

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [useblocks/sphinx-simplepdf#43]
I have a table with 4 columns and the width appears fine in the HTML, but overflows to the right in PDF and content breaks. Also I see that the text in the table is center justified.

Below is the code:

```
.. list-table:: Work splitter configuration parameters (``sootballs_bringup/<SITE>/sites.json``)
   :widths: 5 5 25
   :header-rows: 1
   :class: tight-table

   * - Configuration parameters
     - Sample value
     - Description
   * - ``dispatching_options_all_in_capacity_trigger``
     - 1.0
     - A weight that determines if all-in-mode is enabled.
   * - ``dispatching_options_max_block_time``
     - 2.0
     - The time [s] taken by each *TaskAssignment* loop. If ``dispatching_options_max_block_time`` is set to ``0``, no robots can be assigned any task(s).
   * - ``dispatching_options_use_all_in_mode``
     - false
     - (Task Assigner configuration). Enable/disable All-in-mode.
   * - ``dispatching_options_use_visit_table``
     - false (default)
     - (Task Assigner configuration). False does not avoid congestion.
```
Although the width of the 3rd column is 25, it is not reflecting in the PDF.

**PDF Output:**

![image](https://user-images.githubusercontent.com/105263271/195483386-e48bebde-f925-4658-aa87-0508b342aacf.png)

**Comment by danwos** [comment]
The overflow is not nice and definitely a bug in our CSS.

Your other setting 5 5 25 can not work, as your first coulmn contains unbreakable text and therefore takes the space whatever is needed.
As far as I know the sum of all numbers should be also 100, as it describing the relative sizes.

Can you also check, if one of the table CSS classes from  [here ](https://sphinx-simplepdf.readthedocs.io/en/latest/css.html#table-content-wrap) works for you. Thanks.

**Comment by sachin-suresh-rapyuta** [comment]
Checking that. Can you please correct the Demo PDF URL from [Table Size](https://sphinx-simplepdf.readthedocs.io/en/latest/css.html#table-size) section?

**Comment by sachin-suresh-rapyuta** [comment]
@danwos - was there any fix on the CSS to this issue?

**Comment by danwos** [comment]
No nothing yet from my side.
It's currently hard to find some time to care about it.

**Comment by danwos** [comment]
Mhh this should work out of the box, as long as no Javascript is doing fancy stuff.

**Comment by sachin-suresh-rapyuta** [comment]
It is working only in HTML, but on PDF.
