### ISSUE TITLE
Improvement: Generate separate PDFs based on TOC

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [useblocks/sphinx-simplepdf#50]
Just an improvement suggestion:

I have a multiple TOC's in my index.rst. I intend to create separate PDFs for each TOC. Is there a way where I can generate a PDF on the command line or configure it in conf.py for each TOC (using some flags or `caption` text of the TOC)?

Currently, I am commenting out the TOC which I don't need in the PDF.

**Comment by danwos** [comment]
You can use the ``if-collection`` directive from https://sphinx-collections.readthedocs.io/en/latest/directives.html 
to control the toc to use via **Sphinx tags**.

Then you can build docs like:
``sphinx-build -t docs_for_A -b pdf . _build/A/simplepdf``
or
``sphinx-build -t docs_for_B b pdf . _build/B/simplepdf``

Do not use the in-build ``only`` directive from Sphinx, it does nearly the same, but can not be used to manipulate the final doc structure.

**Comment by sachin-suresh-rapyuta** [comment]
Here is my conf.py:

```
.. if-builder:: simplepdf

   .. if-collection:: user_guide

      .. toctree::
         :maxdepth: 2
         :caption: End User Documentation

         /user/user_preface
         /user/getting_started
         ...
         ...
```

Then I build PDF using: `sphinx-build -a -E user_guide -b simplepdf . build/ `

I get `sphinx-build: error: cannot find files ['build']`

**Comment by danwos** [comment]
Argh, I was wrong. ``if-collection`` needs a configured collection and it can be configured to listen on specific sphinx-tags.
https://sphinx-collections.readthedocs.io/en/latest/collections/index.html#tags

So some dummy collection is needed, to use this mechanism. 
Maybe there are better ways, but I don't know any.

I would like to close this issue, as it is not sphinx-SimplePDF related and it's more discussing a general Sphinx topic like "variant handling in sphinx".
