### ISSUE TITLE
Can there be 2 `simplepdf_vars` for generating multiple PDFs

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [useblocks/sphinx-simplepdf#65]
I want to generate 2 PDFs from a single `conf.py` file. Is there such flexibility?

2 PDFs with different `top-right-content` or `cover-bg`.

**Comment by danwos** [comment]
You can combine different solutions to get this done:

1. Use sphinx-tags and set the needed tag during the build command: `sphinx-build -t first_pdf -b simplepdf sources/ build/`
2. Check in `conf.py` if a tag is set:
```python
# Untested, pseudo code
if "first_pdf" in tags:
    simplepdf_vars = {version_A}
else:
     simplepdf_vars = {version_B}  
```
That's it.

Or you could have a different `conf.py` and select via: `sphinx-build -c another_conf.py  -b simplepdf sources/ `

**Comment by sachin-suresh-rapyuta** [comment]
How to define tags? For example, if I simply:
`tags.add('footag')` even after importing them by: `from sphinx.util.tags import Tags`, I get the error: 

"tags" is not defined Pylance[reportUndefinedVariable](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUndefinedVariable)

**Comment by danwos** [comment]
For such common details please ask this question in the related Sphinx community.
They will be able to help you much better and faster than I can.

**Comment by silopolis** [comment]
> You can combine different solutions to get this done:

This would be a nice addition to the config vars docs section, maybe like a Note or Tip

**Comment by sachin-suresh-rapyuta** [comment]
Yes trying this out. Having some issues in the only directive or still unsure how to use the conditional outputting.

**Comment by sachin-suresh-rapyuta** [comment]
> > You can combine different solutions to get this done:
> 
> This would be a nice addition to the config vars docs section, maybe like a Note or Tip

Would be happy to see if you have achieved this or did something similar.
