### ISSUE TITLE
Long inline code within paragraph breaks formatting in PDF

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [useblocks/sphinx-simplepdf#66]
I have an inline code in a paragraph like below in RST :

To verify the progress of the operation objects obtained in :ref:`Step 1<Step 1: Upload CSV documents>`, use the ``GET /v1/operations/`` endpoint. We can conveniently pass the operation object IDs as query parameters to narrow its results. For example: ``GET /v1/operations/?id=<operation_obj_1_id>&id=<operation_obj_2_id>&...&id=<operation_obj_n_id>``.

But, the PDF output for this line has too many white spaces:

![image](https://user-images.githubusercontent.com/105263271/216517866-f8ccb7b5-d997-4666-a5db-e35757c5dea7.png)

**Comment by sachin-suresh-rapyuta** [comment]
I can use the `codeblock`, but I don't see using codeblock for a single line makes sense. There should be a way to fix this line-breaking issue from simplepdf style?

**Comment by danwos** [comment]
I think we need to fix some CSS here. But I'm not sure which rules, yet.
Also our DEMO-PDF has 1-2 examples, which are shown this problem.

Thanks for reporting it.
